
services:
  db:
    image: postgres:15
    container_name: finance-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: finance-server
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: finance-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  db-data:
